#!/usr/bin/env bash
# Writes the two nginx files that make a site behind the Cloudflare proxy see the REAL visitor address and (optionally) refuse
# anyone who is not Cloudflare. Run with sudo; re-run now and then, Cloudflare changes its list rarely. Then: nginx -t && systemctl reload nginx
#   /etc/nginx/snippets/cloudflare-real-ip.conf   include it inside a server block to use CF-Connecting-IP
#   /etc/nginx/conf.d/cloudflare-geo.conf         defines $from_cloudflare (1 when the connection really comes from Cloudflare)
set -euo pipefail
V4="$(curl -fsS https://www.cloudflare.com/ips-v4/)"
V6="$(curl -fsS https://www.cloudflare.com/ips-v6/)"
test -n "$V4" -a -n "$V6"
{
  echo "# generated by deploy/qas/gen-cloudflare-nginx.sh on $(date -u +%F)"
  for r in $V4 $V6; do echo "set_real_ip_from $r;"; done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > /etc/nginx/snippets/cloudflare-real-ip.conf
{
  echo "# generated by deploy/qas/gen-cloudflare-nginx.sh on $(date -u +%F)"
  echo 'geo $realip_remote_addr $from_cloudflare {'
  echo "  default 0;"
  for r in $V4 $V6; do echo "  $r 1;"; done
  echo "}"
} > /etc/nginx/conf.d/cloudflare-geo.conf
echo "written; now run: nginx -t && systemctl reload nginx"
